### ISSUE TITLE
Option --output-path doesn't work after v0.8.15

### ISSUE THREAD

**Issue by Shatur** [mozilla/grcov#1002]
In version 0.8.13 the following command produced `lcov.info` for me:
```bash
grcov target/coverage --binary-path target/debug/ --source-dir . -o lcov.info
```
But after update to 0.8.15 the command doesn't create it and exits with code 0. I believe it caused by migration from `structopt` to `clap`.

**Comment by CosmicHorrorDev** [comment]
This issue seems to predate the `structopt` -> `clap` changes, and seems to be related to the change to add `--output-types` instead

When running the code above neither `output_type` nor `output_types` are passed, so they default to `None` and `Vec::new()` respectively. Then when running through things we run through this logic in `fn main()`

```rust
let output_types = match opt.output_type {
    Some(output_type) => vec![output_type],
    None => opt.output_types,  // `output_type` is `None` so we return an empty vec
};

let output_path = match output_types.len() {
    0 => return,  // <-- *ding ding ding* here's our early return
    1 => opt.output_path.as_deref(),
    _ => match opt.output_path.as_deref() {
        Some(output_path) => {
            if output_path.is_dir() {
                Some(output_path)
            } else {
                panic!("output_path must be a directory when using multiple outputs");
            }
        }
        _ => None,
    },
};
```

Back on 0.8.13 there wasn't an `output_types` and `output_type` would just default to lcov if not provided. Seems like the logic above should set `output_types` to `vec![OutputType::Lcov]` if neither of those flags are set

**Comment by CosmicHorrorDev** [comment]
I feel like we could just make `--output-type` and alias for `--output-types` and then default the value to `vec![OutputType::Lcov]`. If that seems like a reasonable change then I can open a PR. `clap` aliases act as a hidden flag, so it would still allow for `--output-type` to be passed, but it won't show up in the help text, but it seems like it's only an option still for backwards compatibility anyways

Let me know if I'm missing anything. I'm not very familiar with this project
