### ISSUE TITLE
Travis builds broken because of bad formatting

### ISSUE THREAD

**Issue by marco-c** [mozilla/grcov#156]
Something has changed in the dependencies (maybe a new version of rustfmt? Or a new Rust version?), which broke the build: https://travis-ci.org/mozilla/grcov/jobs/402754467

**Comment by gabriel-v** [comment]
That looks like it's going to keep happening, since the code formatting RFC is ongoing.

Do we just `cargo fmt` again and push to master?

Could we pin the rustfmt-preview component version and update it manually from time to time?

Maybe the code formatting would be better off as a separate check that only runs for PRs?

**Comment by marco-c** [comment]
In the ideal world, I'd prefer the PRs not to contain formatting changes (as I want to see only the logic changes). E.g. often, when the PR removes an if, it will also have to contain a lot of formatting changes just because of the linter.
It would be great if the PRs would pass no matter if the formatting is OK, but then the formatting would be applied automatically after the PR is merged.

Not sure if there's a way to achieve this. If we can't think of anything, maybe it's best to pin rustfmt-preview (if there's a way).

**Comment by gabriel-v** [comment]
So that means we should remove the checks from the `script` phase, and run `cargo fmt` in the `deploy` phase. We would need a GitHub bot account to push the formatting commit (if one is needed). Do we have one available?

Travis can deploy to GitHub Pages and GitHub Releases, but I see no generic flow of pushing back to GitHub repositories. There's also [this guilde here](https://gist.github.com/willprice/e07efd73fb7f13f917ea) that treats GitHub pages, but we can surely make it push back to master.

Here's a problem: if we merge a patch and it gets auto-formatted, the formatting commit will trigger another travis build. It won't go on an infinite loop (because we won't push empty commits).

**Comment by marco-c** [comment]
Another option would be to run the formatting only in Travis builds triggered by cron. This way we avoid the problem of a formatting commit triggering another build.
We could also create a PR instead of pushing directly to master, just to make sure someone looks over the changes.

I have a GitHub test account that I used for another project, but maybe it's better to just create a new separate one.

**Comment by marco-c** [comment]
Thinking about this more... Maybe we should run it for every PR and pin the version of rustfmt, otherwise we'll get a very polluted history.

**Comment by gabriel-v** [comment]
Don't see a way to install a specific version with `rustup component add`. We could build `rustfmt` from source, checking out a specific revision, but that will mean more build failures (as both `rustc +nightly` and `rustfmt` are moving targets).

**Comment by marco-c** [comment]
Great... Running it only on PRs without pinning has the big downside that people will get failures which can be totally unrelated from their patch.
Maybe we should disable the check for now and reenable it when things are more stable?

**Comment by marco-c** [comment]
We could install rustfmt-nightly using Cargo, this way we should be able to pin the version.

**Comment by gabriel-v** [comment]
I tried installing a few tagged versions of the library; for all those versions the build failed for some dependency. These `rust-lang-nursery` crates tend to depend on a lot of other `rust-lang-nursery` crates, so when you try to fix a version while still using the nightly compiler, __*boom*__

I say we take this out until they complete the RFC process.
