### ISSUE TITLE
Running on Windows is broken because of symlink usage

### ISSUE THREAD

**Issue by EFanZh** [mozilla/grcov#462]
To reproduce, run the following code with cmd:

```cmd
set CARGO_INCREMENTAL=0
set RUSTFLAGS=-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
set RUSTDOCFLAGS=-Cpanic=abort

cargo +nightly new test-coverage --lib
cd test-coverage
cargo +nightly test

cargo +nightly install grcov
grcov ./target/debug/ -s . -t html --llvm --branch --ignore-not-existing -o ./target/debug/coverage/

start target/debug/coverage/src/lib.rs.html
```

There is no coverage on the report. Also, I have noticed that if I use `nightly-gnu` instead of `nightly`, the result is correct. Maybe the `-Zprofile` is not supported for msvc target?

System informantion:

- Compiler: rustc 1.46.0-nightly (50fc24d8a 2020-06-25)
- OS: Windows 10 version 2004 (OS Build 19041.329)

**Comment by howardmoore** [comment]
I've seen the same issue. I initially wondered if it was due to the use of --llvm, as I was linking with the MSVC linker, but removing that flag resulted in grcov reporting errors. Eventually I found that removing the -Cpanic=abort rustflag solved the problem. I also found I had to turn off control flow guard or my instrumented application crashed with a stack buffer overflow.

**Comment by 0rphon** [comment]
getting the same issue. none of the fixes here worked for me

**Comment by marco-c** [comment]
I'll try to get to this as soon as I get my hands on a Windows machine.

**Comment by lolo32** [comment]
I've got another error on my Windows 10.

Without Administrator rights, it ends with:

    18:53:08 [ERROR] A panic occurred at C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\grcov-0.7.1\src\producer.rs:297: Failed to create
 a symlink "D:\\Projets\\rust\\test_cover\\.\\your_name-8644-12395990519104456799_0.profraw" -> "C:\\Users\\User\\AppData\\Local\\Temp\\.tmpxic1nO\
\your_name-8644-12395990519104456799_0_1.profraw"

If running with admin rights because grcov want to do symlinks:

```cmd
set LLVM_PROFILE_FILE=your_name-%p-%m.profraw
set RUSTFLAGS=-Zinstrument-coverage
cargo +nightly build
cargo +nightly test
grcov . --source-dir . --llvm --binary-path .\target\debug\ --branch --ignore-not-existing --ignore "/*" --output-type html --output-path .\target\debug\coverage
```

    19:04:29 [ERROR] Error while executing llvm tools: Failed to execute "C:\\Users\\User\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\bin\\llvm-profdata.exe" "merge" "-sparse" "C:\\Users\\User\\AppData\\Local\\Temp\\.tmpVTufXj\\your_name-8644-12395990519104456799_0_1.profraw" "C:\\Users\\User\\AppData\\Local\\Temp\\.tmpVTufXj\\default_1.profraw" "-o" "C:\\Users\\User\\AppData\\Local\\Temp\\.tmpVTufXj\\1\\grcov.profdata"
    Le fichier spécifié est introuvable. (os error 2)

Sorry, the error message is in french like my interface. It says that grcov cannot find a file.

Versions informations:

- `rustup 1.23.1 (3df2264a9 2020-11-30)`
- `cargo 1.51.0-nightly (ab64d1393 2021-02-10)`
- `rustc 1.52.0-nightly (07194ffcd 2021-02-10)`
- `grcov 0.7.1`

**Comment by lolo32** [comment]
Sorry, i'm replying to my previous report, I forget to install `llvm-tools-preview`.

```cmd
rustup component add llvm-tools-preview
```

Solved my previous problem, but I got another erro with the same command as the previous one:

    19:58:28 [ERROR] Execution count overflow detected.

**Comment by marco-c** [comment]
@lolo32 does the report look OK? That error can be ignored in most cases.

**Comment by DanielJoyce** [comment]
Just encountered `[ERROR] Execution count overflow detected.` on Linux now.

cargo 1.51.0 (43b129a20 2021-03-16)

DISTRIB_ID=Pop
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Pop!_OS 20.10"

**Comment by marco-c** [comment]
#720 should fix this.
