### ISSUE TITLE
Subfolder will be missed in reports if it has the same name as the root folder

### ISSUE THREAD

**Issue by ko1N** [mozilla/grcov#483]
In my current Rust project I have a workspace that contains a multiple sub-crates.

The git repository is named "memflow" (and so is my folder on disk) and one of the crates inside the project workspace is also named "memflow". In this case grcov will skip over the entire memflow crate for me and not provide any coverage on it whatsoever.

If i rename the root folder on disk to something like memflow_test so that the main crate is at memflow_test/memflow grcov will pick it up.

The project in question can be found here:
https://github.com/memflow/memflow/

I was running grcov as described in the Readme. I additionally added the "--workspace --all-features" flags for the cargo build & cargo test steps.

Best regards,
Patrick

**Comment by tylerhawkes** [comment]
I'm seeing the same thing with a properietary repo.

**Comment by vitorenesduarte** [comment]
I've described the same issue in https://github.com/actions-rs/grcov/issues/73. There I mentioned (https://github.com/actions-rs/grcov/issues/73#issuecomment-635205701) that the issue was not occurring when using Travis. But maybe it was because the format I was using in Travis was `coveralls`, not `lcov`.

Could this issue be specific to the `lcov` format?

**Comment by vitorenesduarte** [comment]
I believe https://github.com/mozilla/grcov/pull/546 fixes this. It seems that the issue was not specific to any format.
