### ISSUE TITLE
Add a Text/Markdown output

### ISSUE THREAD

**Issue by lu-zero** [mozilla/grcov#498]
It would be nice to have an output that's readable from the shell.

**Comment by dbr** [comment]
I would have found something like this very useful when setting up coverage in a CI system - it's a helpful sanity check to have a short summary of coverage results in the log output instead of having to (fully) rely on the report (which with something liek codecov could, possibly, fail to upload)

[coverage.py's](https://coverage.readthedocs.io/en/coverage-5.5/) default report output is a good example:

```
$ coverage report -m
Name                      Stmts   Miss  Cover   Missing
-------------------------------------------------------
my_program.py                20      4    80%   33-35, 39
my_other_module.py           56      6    89%   17-23
-------------------------------------------------------
TOTAL                        76     10    87%
```

Personally I could happily remove the `Missing: 33-35, 39` output column

**Comment by marco-c** [comment]
This would be just a matter of adding a new output format.
